name: docker-build-and-push

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ignite kubemaster
        id: docker_build_ignite_kubemaster
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.ignite-kubemaster
          push: true
          tags: nolancon/ignite-kubemaster:latest
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile     
          push: true
          tags: nolancon/go-dev-env:latest
      -
        name: Build and push ignite
        id: docker_build_ignite
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.ignite      
          push: true
          tags: nolancon/ignite-go-dev-env:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
